// RUN: split-file %s %t
// RUN: graphalg-translate --import-graphalg %t/input.gr > %t/parsed.mlir
// RUN: graphalg-opt %t/parsed.mlir --graphalg-to-core-pipeline --graphalg-verify-loop-bounds --graphalg-explicate-sparsity --graphalg-split-aggregate --graphalg-loop-aggregate --graphalg-to-rel > %t/rel.mlir
// RUN: garel-translate --export-sql %t/rel.mlir > %t/bfs.py
// RUN: touch %t/__init__.py
// RUN: python3 %t/driver.py
// RUN: diff %t/reference.csv %t/output.csv

//--- edges.csv
c0, c1, c2
0,1,true
0,2,true
1,2,true
1,3,true
1,4,true
2,0,true
3,5,true
3,6,true
3,7,true
4,0,true
4,1,true
5,3,true
5,7,true
7,0,true
7,1,true
7,2,true
8,9,true

//--- input.gr
func setDepth(b:bool, iter:int) -> int {
  return cast<int>(b) * (iter + int(2));
}

func BFS(graph: Matrix<s, s, bool>, source: Vector<s, bool>) -> Vector<s, int> {
  v = Vector<int>(graph.nrows);
  v<source>[:] = int(1);

  frontier = source;
  reach = source;

  for i in graph.nrows {
    step = Vector<bool>(graph.nrows);
    step<!reach> = frontier * graph;

    v += apply(setDepth, step, i);

    frontier = step;
    reach += step;
  } until frontier.nvals == int(0);

  return v;
}

//--- driver.py
from bfs import BFS
import duckdb
from pathlib import Path

dir = Path(__file__).parent
conn = duckdb.connect()
vertices = conn.sql("SELECT generate_series AS c0 FROM generate_series(0, 7)")
edges = conn.read_csv(dir / 'edges.csv', dtype=['int64', 'int64', 'bool'])
source = conn.sql("SELECT 0 AS c0, true::BOOL AS c1")

res = BFS(conn, edges, source, vertices)
res.sort('c0').to_csv(str(dir / 'output.csv'))

//--- reference.csv
c0,c1
0,1
1,2
2,2
3,3
4,3
5,4
6,4
7,4
