// RUN: split-file %s %t
// RUN: graphalg-translate --import-graphalg %t/input.gr > %t/parsed.mlir
// RUN: graphalg-opt %t/parsed.mlir --graphalg-to-core-pipeline --graphalg-verify-loop-bounds --graphalg-explicate-sparsity --graphalg-split-aggregate --graphalg-loop-aggregate --graphalg-to-rel > %t/rel.mlir
// RUN: garel-translate --export-sql %t/rel.mlir > %t/bfs.py
// RUN: touch %t/__init__.py
// RUN: python3 %t/driver.py
// RUN: diff %t/reference.csv %t/output.csv

//--- edges.csv
c0, c1, c2
0,1,TRUE
0,2,TRUE
1,2,TRUE
1,3,TRUE
1,4,TRUE
2,0,TRUE
3,5,TRUE
3,6,TRUE
3,7,TRUE
4,0,TRUE
4,1,TRUE
5,3,TRUE
5,7,TRUE
7,0,TRUE
7,1,TRUE
7,2,TRUE
8,9,TRUE

//--- input.gr
func setDepth(b:bool, iter:int) -> int {
  return cast<int>(b) * (iter + int(2));
}

func BFS(graph: Matrix<s, s, bool>, source: Vector<s, bool>) -> Vector<s, int> {
  v = Vector<int>(graph.nrows);
  v<source>[:] = int(1);

  frontier = source;
  reach = source;

  for i in graph.nrows {
    step = Vector<bool>(graph.nrows);
    step<!reach> = frontier * graph;

    v += apply(setDepth, step, i);

    frontier = step;
    reach += step;
  } until frontier.nvals == int(0);

  return v;
}

//--- driver.py
from bfs import BFS
import duckdb
from pathlib import Path

dir = Path(__file__).parent
conn = duckdb.connect()
vertices = conn.sql("SELECT generate_series AS c0 FROM generate_series(0, 10)")
edges = conn.read_csv(dir / 'edges.csv', dtype=['int64', 'int64', 'bool'])
source = conn.sql("SELECT 0 AS c0, true::BOOL AS c1")

res = BFS(conn, edges, source, vertices)
res.sort('c0').to_csv(str(dir / 'output.csv'))

//--- reference.m
0 0 1 : i64
1 0 2 : i64
2 0 2 : i64
3 0 3 : i64
4 0 3 : i64
5 0 4 : i64
6 0 4 : i64
7 0 4 : i64
