// RUN: split-file %s %t
// RUN: graphalg-translate --import-graphalg %t/input.gr > %t/parsed.mlir
// RUN: graphalg-opt --graphalg-to-core-pipeline --graphalg-set-dimensions='func=WCC args=9x9' %t/parsed.mlir > %t/exec.mlir
// RUN: graphalg-exec %t/exec.mlir WCC %t/graph.m | diff - %t/output.m

//--- graph.m
0 1
0 2
1 0
1 2
1 3
3 1
5 6
5 7
6 5
8 2

//--- input.gr
func WCC(graph: Matrix<s, s, bool>) -> Matrix<s, s, bool> {
  id = Vector<bool>(graph.nrows);
  id[:] = bool(true);
  label = diag(id);

  for i in graph.nrows {
    // Keep current label
    alternatives = label;
    // Labels reachable with a forward step
    alternatives += graph * label;
    // Labels reachable with a backward step
    alternatives += graph.T * label;

    // Select a new label
    label = pickAny(alternatives);
  }

  return label;
}

//--- output.m
0 0 true
1 0 true
2 0 true
3 0 true
4 4 true
5 5 true
6 5 true
7 5 true
8 0 true
