// RUN: split-file %s %t
// RUN: graphalg-exec %t/input.gr SSSP %t/graph.e %t/source.v | diff - %t/output.e

//--- graph.e
1 2 0.5
1 3 5.0
1 4 5.0
2 5 0.5
3 4 2.0
5 6 0.5
6 3 0.5
6 10 23.0
7 1 1.0
7 8 3.2
8 10 0.2
9 10 0.1
10 7 8.0

//--- source.v
1

//--- input.gr
// CHECK:
func SSSP(
        graph: Matrix<s1, s1, trop_real>,
        source: Vector<s1, bool>) -> Vector<s1, trop_real> {
    v = cast<trop_real>(source);
    for i in graph.nrows {
        v += v * graph;
    }
    return v;
}

//--- output.e
1 0.0
2 0.5
3 2.0
4 4.0
5 1.0
6 1.5
7 32.5
8 35.7
9 infinity
10 24.5
