// RUN: parse --import-graphalg < %s | FileCheck %s

// CHECK-LABEL: @ReduceRows
func ReduceRows(m:Matrix<s, s, int>) -> Vector<s, int> {
    // CHECK: graphalg.reduce %arg0 : <#dim x #dim x i64> -> <#dim x 1 x i64>
    return reduceRows(m);
}

// CHECK-LABEL: @ReduceCols
func ReduceCols(m:Matrix<s, s, int>) -> Matrix<1, s, int> {
    // CHECK: graphalg.reduce %arg0 : <#dim x #dim x i64> -> <1 x #dim x i64>
    return reduceCols(m);
}

// CHECK-LABEL: @Reduce
func Reduce(m:Matrix<s, s, int>) -> int {
    // CHECK: graphalg.reduce %arg0 : <#dim x #dim x i64> -> <1 x 1 x i64>
    return reduce(m);
}
